const entries=[
{era:"13th–14th century",title:"Sculptural traces near Vagheshvar",mr:"वाघेश्वर मंदिराजवळील शिल्प अवशेष",text:"A Nandi image and a sculpture beside the ruined barava have been dated stylistically to the 13th–14th century. This dates the surviving objects, not necessarily the present temple building.",status:"Supported"},
{era:"18th century",title:"Maratha-period temples",mr:"मराठा काळातील मंदिरे",text:"Researchers assess the Khanderaya and Vagheshvar temples as probable 18th-century structures. No inscription at the site confirms an exact construction year.",status:"Supported"},
{era:"Late 1870s",title:"Vasudev Balwant Phadke and Dhamari",mr:"वासुदेव बळवंत फडके आणि धामारी",text:"Local memory links Dhamari to a raid by Phadke to raise funds against British rule. The exact date still needs a primary archival citation.",status:"Oral-history lead"},
{era:"2011",title:"Dhamari in the Census",mr:"जनगणनेतील धामारी",text:"Village code 555591. Population 3,909 in 817 households: 1,986 males and 1,923 females. Recorded area: 4,801 hectares.",status:"Documented"}];
const sources=[
["Census 2011: Primary Census Abstract, Pune","Census of India","https://censusindia.gov.in/nada/index.php/catalog/6712"],
["Village Directory, Pune, 2001","Census of India","https://censusindia.gov.in/nada/index.php/catalog/23808/study-description"],
["Khanderaya and Vagheshvar Temples, Dhamari","Tattva Heritage Foundation","https://heritagetemples.org/pune-project/khanderaya-and-vagheshvar-temples"],
["Dhamari Nagarkot field note","Durgbharari","https://durgbharari.in/dhamari/"],
["Draft Development Plan 2021–2041","PMRDA","https://geoportal.pmrda.gov.in/DP-PMRDA-V1/"]];
export default function App(){return <main>
<nav className="nav shell"><a className="brand" href="#top"><span>धा</span>Dhamari Archive</a><div className="navlinks"><a href="#history">History</a><a href="#heritage">Heritage</a><a href="#sources">Sources</a></div></nav>
<header className="hero" id="top"><div className="shell heroGrid"><div><p className="eyebrow">Shirur · Pune · Maharashtra</p><h1>धामारी<br/><em>Dhamari</em></h1><p className="lede">A living village. A layered past. An open, sourced record of its land, temples, memories and people.</p><div className="actions"><a className="button" href="#history">Explore the timeline</a><a href="#method"><b>How facts are checked →</b></a></div></div><aside className="placeCard"><p className="label">Village record</p><dl><div><dt>Census code</dt><dd>555591</dd></div><div><dt>Population</dt><dd>3,909 <small>in 2011</small></dd></div><div><dt>Area</dt><dd>4,801 <small>hectares</small></dd></div><div><dt>PIN</dt><dd>412403</dd></div></dl><p className="coords">18.789° N · 74.098° E</p></aside></div></header>
<section className="portrait shell" id="heritage"><p className="sectionNo">01 / Village portrait</p><div className="split"><h2>More than a dot<br/>on the map.</h2><div><p className="standfirst">On the Shikrapur–Pabal road, Dhamari preserves old sculpture, Maratha-period sacred architecture, a ruined stepwell and the remaining gate of a village fortification.</p><p>Its Khanderaya temple anchors a living annual tradition. The east-facing Vagheshvar temple adds older layers whose dates must be read with care.</p></div></div><div className="features"><article className="ochre"><span>Architecture</span><h3>Khanderaya Temple</h3><p>A probable 18th-century temple. Khanderaya is recorded as the village deity.</p></article><article className="dark"><span>Water heritage</span><h3>Vagheshvar & the barava</h3><p>An east-facing Shiva temple beside a ruined stepped water structure.</p></article><article className="sand"><span>Fortified village</span><h3>The Nagarkot gate</h3><p>One gate and partial bastions survive. It now bears Phadke’s name.</p></article></div></section>
<section className="history" id="history"><div className="shell"><p className="sectionNo pale">02 / Evidence-led timeline</p><div className="historyHead"><h2>What we know.<br/><em>What needs proof.</em></h2><p>Every entry carries an evidence label. Local memory remains visible without being silently promoted into proven fact.</p></div>{entries.map(x=><article className="event" key={x.title}><p className="era">{x.era}</p><div><span className={`badge ${x.status==="Documented"?"verified":x.status.startsWith("Oral")?"lead":""}`}>{x.status}</span><h3>{x.title}</h3><p className="mr">{x.mr}</p><p>{x.text}</p></div></article>)}</div></section>
<section className="method shell" id="method"><p className="sectionNo">03 / Research method</p><div className="split"><h2>History without<br/>the guesswork.</h2><div className="principles"><article><b>1</b><h3>Start with records</h3><p>Government and institutional material forms the base.</p></article><article><b>2</b><h3>Preserve memory</h3><p>Oral accounts stay visible with a clear label.</p></article><article><b>3</b><h3>Show uncertainty</h3><p>Architectural dates remain assessments, not certainties.</p></article></div></div></section>
<section className="sources" id="sources"><div className="shell"><p className="sectionNo">04 / Source register</p><div className="sourceHead"><h2>Read the record<br/>for yourself.</h2><p>The archive can grow as gazette records, photographs, inscriptions and oral histories are verified.</p></div><div className="sourceList">{sources.map(([t,p,u],i)=><a href={u} target="_blank" rel="noreferrer" key={u}><span>0{i+1}</span><div><b>{t}</b><small>{p}</small></div><i>↗</i></a>)}</div></div></section>
<footer><div className="shell footerGrid"><div><p className="footerTitle">धामारीचा इतिहास,<br/>धामारीच्या लोकांसाठी.</p><p>Dhamari’s history, for Dhamari’s people.</p></div><div><b>Corrections welcome</b><p>Have a document, dated photograph, inscription or family record? Add it to the next verified edition.</p></div></div><div className="shell footnote">Independent public-history project · Sources accessed August 2026 · No claim of official village affiliation</div></footer>
</main>}
