const entries=[
{era:"13th–14th century",title:"Sculptural traces near Vagheshvar",mr:"वाघेश्वर मंदिराजवळील शिल्प अवशेष",text:"A Nandi image and a sculpture beside the ruined barava have been dated stylistically to the 13th–14th century. This dates the surviving objects, not necessarily the present temple building.",status:"Supported"},
{era:"18th century",title:"Maratha-period temples",mr:"मराठा काळातील मंदिरे",text:"Researchers assess the Khanderaya and Vagheshvar temples as probable 18th-century structures. No inscription at the site confirms an exact construction year.",status:"Supported"},
{era:"20 February 1879",title:"Phadke's first recorded raid",mr:"वासुदेव बळवंत फडके यांची धामारीतील कारवाई",text:"Published biographical accounts identify Dhamari as the site of the first raid associated with Vasudev Balwant Phadke's revolutionary campaign. The money was reportedly taken from the house where colonial revenue was held.",status:"Published account"},
{era:"2011",title:"Dhamari in the Census",mr:"जनगणनेतील धामारी",text:"Village code 555591. Population 3,909 in 817 households: 1,986 males and 1,923 females. Recorded area: 4,801 hectares.",status:"Documented"},
{era:"June–August 2026",title:"Proposed Pabal–Dhamari MIDC advances",mr:"प्रस्तावित पाबळ–धामारी एमआयडीसी",text:"News reports say Maharashtra notified land for a proposed 743-hectare industrial estate in June 2026. By 26 August, the acquisition process had begun and 'notified area' entries were being placed on affected 7/12 land records. The estate is proposed—not yet built.",status:"Current report"}
];
const sources=[
["Census 2011: Primary Census Abstract, Pune","Census of India","https://censusindia.gov.in/nada/index.php/catalog/6712"],
["Village Directory, Pune, 2001","Census of India","https://censusindia.gov.in/nada/index.php/catalog/23808/study-description"],
["Khanderaya and Vagheshvar Temples, Dhamari","Tattva Heritage Foundation","https://heritagetemples.org/pune-project/khanderaya-and-vagheshvar-temples"],
["Dhamari Nagarkot field note","Durgbharari","https://durgbharari.in/dhamari/"],
["Gangasagar Talav: OpenStreetMap feature 989003631","OpenStreetMap contributors","https://www.openstreetmap.org/way/989003631"],
["Pabal–Dhamari: proposed 743-hectare MIDC","Sarkarnama, 26 August 2026","https://sarkarnama.esakal.com/pune/another-big-midc-for-pune-not-chakan-or-ranjangaon-new-743-hectare-industrial-hub-to-come-up-in-this-area-aau85-sm89"],
["Pabal–Dhamari MIDC report","Pune Mirror, 26 August 2026","https://punemirror.com/city/pune/pabal-dhamari-midc-743-hectare-industrial-estate-pune/"],
["Vasudev Balwant Phadke","Press Information Bureau, Government of India","https://www.pib.gov.in/newsite/printrelease.aspx?relid=148384"]
];
const phadkeImage="https://upload.wikimedia.org/wikipedia/commons/9/9d/Vasudev_Balwant_Phadke.png";
export default function App(){return <main>
<nav className="nav shell"><a className="brand" href="#top"><span>धा</span>Dhamari Archive</a><div className="navlinks"><a href="#history">History</a><a href="#heritage">Heritage</a><a href="#gangasagar">Gangasagar</a><a href="#midc">MIDC</a><a href="#sources">Sources</a></div></nav>
<header className="hero" id="top"><div className="shell heroGrid"><div><p className="eyebrow">Shirur · Pune · Maharashtra</p><h1>धामारी<br/><em>Dhamari</em></h1><p className="lede">A living village. A layered past. An open, sourced record of its land, temples, memories and people.</p><div className="actions"><a className="button" href="#history">Explore the timeline</a><a href="#method"><b>How facts are checked →</b></a></div></div><aside className="placeCard"><p className="label">Village record</p><dl><div><dt>Census code</dt><dd>555591</dd></div><div><dt>Population</dt><dd>3,909 <small>in 2011</small></dd></div><div><dt>Area</dt><dd>4,801 <small>hectares</small></dd></div><div><dt>PIN</dt><dd>412403</dd></div></dl><p className="coords">18.789° N · 74.098° E</p></aside></div></header>
<section className="portrait shell" id="heritage"><p className="sectionNo">01 / Village portrait</p><div className="split"><h2>More than a dot<br/>on the map.</h2><div><p className="standfirst">On the Shikrapur–Pabal road, Dhamari preserves old sculpture, Maratha-period sacred architecture, a ruined stepwell and the remaining gate of a village fortification.</p><p>Its Khanderaya temple anchors a living annual tradition. The east-facing Vagheshvar temple adds older layers whose dates must be read with care.</p></div></div><div className="features"><article className="ochre"><span>Architecture</span><h3>Khanderaya Temple</h3><p>A probable 18th-century temple. Khanderaya is recorded as the village deity.</p></article><article className="dark"><span>Water heritage</span><h3>Vagheshvar & the barava</h3><p>An east-facing Shiva temple beside a ruined stepped water structure.</p></article><article className="sand"><span>Fortified village</span><h3>The Nagarkot gate</h3><p>One gate and partial bastions survive. It now bears Phadke's name.</p></article></div>
<div className="mediaGrid"><figure className="phadkePhoto"><img src={phadkeImage} alt="Portrait of Vasudev Balwant Phadke"/><figcaption><b>Vasudev Balwant Phadke</b><span>Image: Lok Sabha Secretariat via Wikimedia Commons · CC BY-SA 4.0 · unmodified</span><a href="https://commons.wikimedia.org/wiki/File:Vasudev_Balwant_Phadke.png" target="_blank" rel="noreferrer">Source and licence ↗</a></figcaption></figure><aside className="photoNotice"><p className="label">Local photographs wanted</p><h3>Help document Dhamari accurately.</h3><p>No Dhamari temple or Gangasagar photograph found online carried a clear reusable licence. Copyrighted images have not been copied. Residents can contribute original, dated photographs with the photographer's permission.</p></aside></div></section>
<section className="water" id="gangasagar"><div className="shell"><p className="sectionNo pale">02 / Water landscape</p><div className="waterGrid"><div><p className="eyebrow">गंगासागर तलाव</p><h2>Gangasagar Talav</h2><p className="standfirst">A mapped reservoir southwest of Dhamari, near Mukhai.</p><p>OpenStreetMap records the water body as way 989003631 at approximately 18.7778° N, 74.0898° E. Publicly available sources reviewed for this edition do not establish its construction date, capacity or official irrigation history, so those details remain open research questions.</p><a className="textLink" href="https://www.openstreetmap.org/way/989003631" target="_blank" rel="noreferrer">Open the map record →</a></div><figure className="mapFrame"><iframe title="OpenStreetMap view of Gangasagar Talav" src="https://www.openstreetmap.org/export/embed.html?bbox=74.075%2C18.767%2C74.105%2C18.789&amp;layer=mapnik&amp;marker=18.7778%2C74.0898" loading="lazy"></iframe><figcaption>Map © OpenStreetMap contributors · ODbL</figcaption></figure></div></div></section>
<section className="history" id="history"><div className="shell"><p className="sectionNo pale">03 / Evidence-led timeline</p><div className="historyHead"><h2>What we know.<br/><em>What needs proof.</em></h2><p>Every entry carries an evidence label. Local memory remains visible without being silently promoted into proven fact.</p></div>{entries.map(x=><article className="event" key={x.title}><p className="era">{x.era}</p><div><span className={"badge "+(x.status==="Documented"?"verified":x.status==="Current report"?"current":"")}>{x.status}</span><h3>{x.title}</h3><p className="mr">{x.mr}</p><p>{x.text}</p></div></article>)}</div></section>
<section className="midc" id="midc"><div className="shell"><p className="sectionNo">04 / Current development</p><div className="midcHead"><div><p className="eyebrow">Status checked 30 August 2026</p><h2>Proposed Pabal–Dhamari MIDC</h2></div><div className="statusCard"><span>Current status</span><strong>Notified / acquisition underway</strong><small>Not a completed industrial estate</small></div></div><div className="factGrid"><article><b>743 ha</b><span>reported proposed area</span></article><article><b>June 2026</b><span>reported state notification</span></article><article><b>26 Aug 2026</b><span>latest report reviewed</span></article></div><div className="midcCopy"><div><h3>What has happened</h3><p>Sarkarnama and Pune Mirror report that MIDC began the land-acquisition process for a 743-hectare estate in the Pabal–Dhamari belt on the Shirur–Khed border. The reports say “notified area” remarks were being entered on affected 7/12 extracts after correspondence between the Pune subdivision and Shirur tehsil offices.</p></div><div><h3>What remains uncertain</h3><p>The reviewed material does not yet confirm a construction start date, completion date, tenant industries, final employment count, compensation awards or operational water demand. Claims about rising land prices, jobs and infrastructure are expectations, not completed outcomes.</p></div></div><div className="newsNote"><b>Research note</b><p>This section reports the latest publicly available news, not legal advice. Affected landholders should verify their own 7/12 extract and acquisition notices with the Shirur Tahsil office or MIDC.</p></div></div></section>
<section className="method shell" id="method"><p className="sectionNo">05 / Research method</p><div className="split"><h2>History without<br/>the guesswork.</h2><div className="principles"><article><b>1</b><h3>Start with records</h3><p>Government and institutional material forms the base.</p></article><article><b>2</b><h3>Preserve memory</h3><p>Oral accounts stay visible with a clear label.</p></article><article><b>3</b><h3>Show uncertainty</h3><p>Architectural dates and current proposals are labelled by evidence status.</p></article></div></div></section>
<section className="sources" id="sources"><div className="shell"><p className="sectionNo">06 / Source register</p><div className="sourceHead"><h2>Read the record<br/>for yourself.</h2><p>The archive can grow as gazette records, photographs, inscriptions and oral histories are verified.</p></div><div className="sourceList">{sources.map(([t,p,u],i)=><a href={u} target="_blank" rel="noreferrer" key={u}><span>{String(i+1).padStart(2,"0")}</span><div><b>{t}</b><small>{p}</small></div><i>↗</i></a>)}</div></div></section>
<footer><div className="shell footerGrid"><div><p className="footerTitle">धामारीचा इतिहास,<br/>धामारीच्या लोकांसाठी.</p><p>Dhamari's history, for Dhamari's people.</p></div><div><b>Corrections welcome</b><p>Have a document, dated photograph, inscription, acquisition notice or family record? Add it to the next verified edition.</p></div></div><div className="shell footnote">Independent public-history project · Sources checked 30 August 2026 · No claim of official village affiliation</div></footer>
</main>}