import {blogPosts} from "./blogPosts";
import internetUpdates from "./data/internetUpdates.json";
import {CountUp} from "./CountUp";
import {curatedNews,historyEntries,sources} from "./content";
import {useEffect,useLayoutEffect,useState} from "react";

type Page="home"|"history"|"latest-news"|"midc"|"blog"|"media";
type InternetUpdate={id:string;title:string;source:string;sourceUrl:string;publishedAt:string;status:"पडताळणी प्रलंबित"};
const page=(document.body.dataset.page||"home") as Page;
const phadkeImage="https://upload.wikimedia.org/wikipedia/commons/c/c2/Vasudev_Balwant_Phadke.png";
const newsKey=(value:string)=>value.normalize("NFKC").toLocaleLowerCase("mr").replace(/[^\p{L}\p{N}]+/gu," ").trim();

function Nav(){return <nav className="nav shell" aria-label="मुख्य नेव्हिगेशन"><a className="brand" href="/"><span>धा</span>धामारी अभिलेख</a><div className="navlinks"><a className="navHome" href="/">मुख्यपृष्ठ</a><details className="navGroup"><summary>गाव</summary><div><a href="/history/">इतिहास</a><a href="/blog/">लेख</a></div></details><details className="navGroup"><summary>घडामोडी</summary><div><a href="/latest-news/">ताज्या बातम्या</a><a href="/midc/">MIDC अपडेट</a></div></details><a href="/media/">माध्यमे</a></div></nav>}
function Footer(){return <footer><div className="shell footerGrid"><p className="footerTitle">धामारीचा इतिहास,<br/>धामारीच्या लोकांसाठी.</p><div><b>दुरुस्त्यांचे स्वागत आहे</b><p>तुमच्याकडे कागदपत्र, दिनांकित छायाचित्र, शिलालेख किंवा अधिकृत नोटीस असल्यास अभिलेखात समाविष्ट करण्यासाठी पाठवा.</p></div></div><div className="shell footnote">स्वतंत्र सार्वजनिक इतिहास प्रकल्प · गावाच्या अधिकृत प्रतिनिधित्वाचा दावा नाही</div></footer>}
function PageHero({eyebrow,title,lede}:{eyebrow:string;title:string;lede:string}){return <header className="pageHero"><div className="shell"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{lede}</p></div></header>}
function MotionObserver(){useLayoutEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const targets=document.querySelectorAll<HTMLElement>("main>header,main>section,.event,.newsCard,.blogGrid article,.embedCard,.videoGrid article,.features article,.sourceList a");targets.forEach((target,index)=>{target.classList.add("revealItem");target.style.setProperty("--revealDelay",`${Math.min(index%4,3)*70}ms`)});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add("isVisible");observer.unobserve(entry.target)}),{threshold:.08,rootMargin:"0px 0px -45px"});targets.forEach(target=>observer.observe(target));return()=>observer.disconnect()},[]);return null}
function Intro(){const [visible,setVisible]=useState(()=>!sessionStorage.getItem("dhamari-intro-seen"));const [leaving,setLeaving]=useState(false);useEffect(()=>{if(!visible)return;document.body.classList.add("introOpen");const leave=window.setTimeout(()=>setLeaving(true),1900);const finish=window.setTimeout(()=>{sessionStorage.setItem("dhamari-intro-seen","1");setVisible(false)},2550);return()=>{window.clearTimeout(leave);window.clearTimeout(finish);document.body.classList.remove("introOpen")}},[visible]);const close=()=>{sessionStorage.setItem("dhamari-intro-seen","1");setLeaving(true);window.setTimeout(()=>setVisible(false),650)};if(!visible)return null;return <div className={`introScreen${leaving?" introLeaving":""}`} role="dialog" aria-label="धामारी अभिलेख परिचय"><div className="introMark">धा</div><p>शिरूर · पुणे · महाराष्ट्र</p><h1>धामारी</h1><div className="introLine"></div><span>इतिहास · वारसा · लोकस्मृती · वर्तमान</span><button type="button" onClick={close}>पुढे जा →</button></div>}
function Layout({children,intro=false}:{children:React.ReactNode;intro?:boolean}){return <main>{intro&&<Intro/>}<MotionObserver/><Nav/>{children}<Footer/></main>}

function Home(){return <Layout intro><header className="hero"><div className="shell heroGrid"><div><p className="eyebrow">शिरूर · पुणे · महाराष्ट्र</p><h1>धामारी<br/><em>Dhamari</em></h1><p className="lede">भूमी, मंदिरे, लोकस्मृती आणि वर्तमान घडामोडींचा संदर्भाधारित खुला अभिलेख.</p><div className="actions"><a className="button" href="/history/">ऐतिहासिक घटनाक्रम</a><a href="/latest-news/"><b>ताज्या बातम्या →</b></a></div></div><aside className="placeCard"><p className="label">गावाची नोंद</p><dl><div><dt>जनगणना संकेतांक</dt><dd>५५५५९१</dd></div><div><dt>लोकसंख्या</dt><dd><CountUp value={3909}/> <small>२०११ मध्ये</small></dd></div><div><dt>क्षेत्रफळ</dt><dd><CountUp value={4801}/> <small>हेक्टर</small></dd></div><div><dt>PIN</dt><dd>४१२४०३</dd></div></dl><p className="coords">18.789° N · 74.098° E</p></aside></div></header>
<section className="profile shell"><p className="sectionNo">०१ / जनगणना २०११</p><div className="profileHead"><div><p className="eyebrow">गाव एका नजरेत</p><h2>लोक, भूमी<br/>आणि उपजीविका.</h2></div><p>ही आकडेवारी २०११ च्या जनगणनेची ऐतिहासिक स्थिती दर्शवते. अधिकृत गाव संकेतांक <b>५५५५९१</b> आहे.</p></div><div className="statGrid"><article><b><CountUp value={3909}/></b><span>एकूण लोकसंख्या</span></article><article><b><CountUp value={817}/></b><span>कुटुंबे</span></article><article><b><CountUp value={968}/></b><span>दर १,००० पुरुषांमागे स्त्रिया</span></article><article><b><CountUp value={72.01} decimals={2}/>%</b><span>एकूण साक्षरता</span></article></div></section>
<section className="portrait shell"><p className="sectionNo">०२ / गावाचा वारसा</p><div className="split"><h2>नकाशावरील एका<br/>बिंदूपेक्षा अधिक.</h2><div><p className="standfirst">धामारीमध्ये प्राचीन शिल्पे, मराठाकालीन धार्मिक वास्तू, भग्न बारव आणि तटबंदीचे अवशेष जतन झाले आहेत.</p><p>खंडेराया मंदिर गावाच्या वार्षिक परंपरेचे केंद्र आहे. पूर्वाभिमुख वाघेश्वर मंदिराजवळ १३वे–१४वे शतक मानली जाणारी शिल्पे आहेत. नगरकोटचे एक प्रवेशद्वार आणि बुरुजांचे काही भाग शिल्लक आहेत.</p></div></div><div className="features"><article className="ochre"><span>वास्तुकला</span><h3>खंडेराया मंदिर</h3><p>बहुधा अठराव्या शतकातील मंदिर आणि गावाचे ग्रामदैवत.</p></article><article className="dark"><span>जलवारसा</span><h3>वाघेश्वर आणि बारव</h3><p>भग्न पायऱ्यांच्या जलरचनेशेजारी असलेले पूर्वाभिमुख शिवमंदिर.</p></article><article className="sand"><span>तटबंदीचे गाव</span><h3>नगरकोट प्रवेशद्वार</h3><p>गावाच्या तटबंदीचे उरलेले प्रवेशद्वार आणि बुरुजांचे भाग.</p></article></div><div className="mediaGrid"><figure className="phadkePhoto"><img src={phadkeImage} alt="वासुदेव बळवंत फडके यांचे छायाचित्र" loading="lazy"/><figcaption><b>वासुदेव बळवंत फडके</b><span>लोकसभा सचिवालय · Wikimedia Commons · CC BY-SA 4.0</span><a href="https://commons.wikimedia.org/wiki/File:Vasudev_Balwant_Phadke.png">स्रोत आणि परवाना ↗</a></figcaption></figure><aside className="photoNotice"><p className="label">स्थानिक छायाचित्रे</p><h3>धामारीची अचूक दृश्यनोंद तयार करण्यास मदत करा.</h3><p>छायाचित्रकाराच्या परवानगीसह मूळ व दिनांकित छायाचित्रे ग्रामस्थ देऊ शकतात.</p></aside></div></section>
<section className="water"><div className="shell"><p className="sectionNo pale">०३ / गंगासागर तलाव</p><div className="waterGrid"><div><h2>गंगासागर तलाव</h2><p className="standfirst">धामारीच्या नैऋत्येस, मुखईजवळ नकाशावर नोंदलेला जलाशय.</p><p>OpenStreetMap वर way 989003631 म्हणून नोंद आहे. बांधकाम वर्ष, क्षमता आणि अधिकृत सिंचन इतिहासासाठी प्राथमिक शासकीय नोंदींची पुढील पडताळणी आवश्यक आहे.</p><a className="textLink" href="https://www.openstreetmap.org/way/989003631" target="_blank" rel="noreferrer">नकाशाची नोंद उघडा →</a></div><figure className="mapFrame"><iframe title="धामारी आणि गंगासागर तलावाचा OpenStreetMap नकाशा" src="https://www.openstreetmap.org/export/embed.html?bbox=74.075%2C18.767%2C74.105%2C18.789&amp;layer=mapnik&amp;marker=18.7778%2C74.0898" loading="lazy"></iframe><figcaption>नकाशा © OpenStreetMap योगदानकर्ते · ODbL</figcaption></figure></div></div></section>
<section className="smart"><div className="shell"><p className="sectionNo">०४ / शेती आणि ग्रामविकास</p><div className="smartGrid"><div><p className="eyebrow">५ मार्च २०२५</p><h2>RuTAGe स्मार्ट व्हिलेज सेंटर</h2><p>विज्ञान आश्रम, Agro Rangers आणि N. K. Orchid College यांच्या सहभागाने सौर वाळवण, माती-पिक निरीक्षण आणि शेतमाल प्रक्रियेची साधने उपलब्ध झाली.</p></div><div className="smartCards"><article><b><CountUp value={100}/> किलो/दिवस</b><span>सौर वाळवण यंत्राची नमूद क्षमता</span></article><article><b>उपग्रह सल्ला</b><span>पीक व माती आरोग्य निरीक्षण</span></article></div></div></div></section><Sources/></Layout>}

function History(){return <Layout><PageHero eyebrow="पुराव्याधारित कालरेषा" title="धामारीचा इतिहास" lede="दस्तऐवजीकृत नोंदी, प्रकाशित अभ्यास आणि स्पष्टपणे ओळख दिलेली लोकस्मृती."/><section className="history pageSection"><div className="shell">{historyEntries.map(x=><article className="event" key={x.era+x.title}><p className="era">{x.era}</p><div><span className={`badge ${x.status==="दस्तऐवजीकृत"?"verified":x.status==="नवीनतम वृत्त"?"current":""}`}>{x.status}</span><h2>{x.title}</h2><p className="mr">{x.mr}</p><p>{x.text}</p></div></article>)}</div></section></Layout>}

function LatestNews(){const automated=(internetUpdates as InternetUpdate[]).filter(item=>!curatedNews.some(curated=>{const automatedTitle=newsKey(item.title),curatedTitle=newsKey(curated.title);return automatedTitle.includes(curatedTitle)||curatedTitle.includes(automatedTitle)}));return <Layout><PageHero eyebrow="अद्ययावत नोंदी" title="धामारीच्या ताज्या बातम्या" lede="संदर्भासह निवडक वृत्ते आणि दररोजच्या स्वयंचलित शोधातून मिळालेले नवीन दुवे."/><section className="blog pageSection"><div className="shell"><div className="newsGrid">{curatedNews.map(item=><article className="newsCard" key={item.url}><p className="blogMeta"><span>{item.category}</span>{item.date}</p><h2>{item.title}</h2><p>{item.summary}</p><small>{item.source} · {item.status}</small><a href={item.url} target="_blank" rel="noreferrer">मूळ स्रोत वाचा →</a></article>)}</div>{automated.length>0?<><h2 className="mediaSubhead">स्वयंचलित शोधातील नवीन दुवे</h2><p className="caveat">खालील दुवे स्वयंचलितरीत्या मिळाले आहेत. ते पडताळलेले तथ्य समजू नयेत.</p><div className="newsGrid">{automated.map(item=><article className="newsCard" key={item.id}><p className="blogMeta"><span>पडताळणी प्रलंबित</span>{new Date(item.publishedAt).toLocaleDateString("mr-IN")}</p><h2>{item.title}</h2><small>{item.source}</small><a href={item.sourceUrl} target="_blank" rel="noreferrer">प्रकाशकाची नोंद उघडा →</a></article>)}</div></>:<p className="emptyState">आजच्या स्वयंचलित शोधात नवीन वेगळी नोंद साठवलेली नाही.</p>}</div></section></Layout>}

function Midc(){return <Layout><PageHero eyebrow="पाबळ · धामारी · खैरनगर" title="पाबळ–धामारी एमआयडीसी अपडेट" lede="प्रस्तावित ७४३ हेक्टर औद्योगिक क्षेत्राची वर्तमान, संदर्भाधारित स्थिती."/><section className="midc pageSection"><div className="shell"><div className="midcHead"><div><p className="eyebrow">स्थिती २ सप्टेंबर २०२६ रोजी अद्ययावत</p><h2>प्रक्रियेला तूर्तास स्थगिती</h2></div><div className="statusCard"><span>सध्याची स्थिती</span><strong>तात्पुरती स्थगिती</strong><small>प्रकल्प रद्द झाल्याची पुष्टी नाही</small></div></div><div className="factGrid"><article><b><CountUp value={743}/> हे.</b><span>पूर्वीच्या वृत्तांतील प्रस्तावित क्षेत्र</span></article><article><b>जून २०२६</b><span>अधिसूचनेचे वृत्त</span></article><article><b>२ सप्टेंबर २०२६</b><span>तपासलेली नवीनतम नोंद</span></article></div><div className="midcCopy"><div><h3>नवीनतम बदल</h3><p>सकाळच्या पुणे मुख्य आवृत्तीतील वृत्तानुसार मुख्यमंत्री देवेंद्र फडणवीस यांनी पाबळ–धामारी–खैरनगर येथील नियोजित एमआयडीसी प्रकल्पाच्या सर्व प्रक्रियेला तूर्तास स्थगिती दिली. माजी गृहमंत्री दिलीप वळसे पाटील आणि सार्वजनिक बांधकाम राज्यमंत्री मेघना बोर्डीकर यांनी शेतकऱ्यांसोबत घेतलेल्या भेटीनंतर हा निर्णय झाल्याचे वृत्तात म्हटले आहे.</p><a className="textLink" href="https://www.esakal.com/pune/pabal-dhamari-midc-project-put-on-hold-devendra-fadnavis-gives-relief-to-farmers-across-743-hectares-of-irrigated-land-sdj87" target="_blank" rel="noreferrer">सकाळवरील पूर्ण बातमी उघडा →</a></div><div><h3>याचा अर्थ काय?</h3><p>ही तात्पुरती स्थगिती आहे. उपलब्ध वृत्त प्रकल्प कायमचा रद्द झाल्याचे सांगत नाही. पुढील शासन आदेश, राजपत्र, एमआयडीसी नोटीस किंवा अधिकृत बैठक नोंद उपलब्ध झाल्यावर स्थिती पुन्हा अद्ययावत करणे आवश्यक आहे.</p></div></div><div className="newsNote"><b>जमीनधारकांसाठी सूचना</b><p>कायदेशीर स्थितीसाठी सातबारा उतारा, वैयक्तिक नोटीस आणि शिरूर तहसील किंवा एमआयडीसीची अधिकृत नोंद तपासा. हा माहितीपर अभिलेख कायदेशीर सल्ला नाही.</p></div></div></section></Layout>}

function Blog(){return <Layout><PageHero eyebrow="धामारी नोंदवही" title="लेख आणि क्षेत्रनोंदी" lede="इतिहास, जनगणना, शेती, जलवारसा आणि विकासावरील संदर्भाधारित लेख."/><section className="blog pageSection"><div className="shell"><div className="blogGrid">{blogPosts.map(post=><article key={post.slug}><p className="blogMeta"><span>{post.category}</span>{post.date}</p><h2>{post.title}</h2>{post.marathiTitle&&<p className="mr">{post.marathiTitle}</p>}<p>{post.summary}</p>{post.sourceUrl?<a href={post.sourceUrl}>स्रोत वाचा →</a>:<span className="archiveLabel">अभिलेख स्पष्टीकरण</span>}</article>)}</div></div></section></Layout>}

function Embed({title,src,url}:{title:string;src:string;url:string}){return <article className="embedCard"><iframe title={title} src={src} loading="lazy" allowFullScreen></iframe><div><b>{title}</b><a href={url} target="_blank" rel="noreferrer">मूळ पोस्ट ↗</a></div></article>}
function Media(){const instagram=[
  ["ऐतिहासिक धामारी","https://www.instagram.com/reel/C-eZb5TgJSG/embed/captioned/","https://www.instagram.com/reel/C-eZb5TgJSG/"],
  ["खंडेराया उत्सव, धामारी","https://www.instagram.com/p/DEmvqSpobR3/embed/captioned/","https://www.instagram.com/p/DEmvqSpobR3/"],
  ["पाबळ–धामारी एमआयडीसी वृत्त","https://www.instagram.com/reel/DciFlGUEpZE/embed/captioned/","https://www.instagram.com/reel/DciFlGUEpZE/"],
  ["RuTAGe स्मार्ट व्हिलेज सेंटर","https://www.instagram.com/p/DJrEC1LTwwa/embed/captioned/","https://www.instagram.com/p/DJrEC1LTwwa/"],
  ["धामारीतील फळबाग शेती","https://www.instagram.com/p/C707kWVy5aX/embed/captioned/","https://www.instagram.com/p/C707kWVy5aX/"]
];const videos=[
  ["HbhiMTXHWaE","ऐतिहासिक धामारी गाव"],
  ["7Puxzof00yg","वाघेश्वर मंदिर आणि बारव"],
  ["PamFxBgRPSI","धामारी नगरकोट"],
  ["rtkz-609NKQ","वासुदेव बळवंत फडके यांची धामारीतील कारवाई"],
  ["I6Ss_85GQZo","धामारीचे खंडोबा मंदिर"],
  ["KCAIJVrv99I","श्री खंडेराया उत्सव, धामारी २०२५"]
];return <Layout><PageHero eyebrow="Instagram · YouTube" title="धामारीचे माध्यम संग्रह" lede="गावाचा इतिहास, वारसा, शेती आणि उत्सव यांवरील सार्वजनिक पोस्ट, रील्स आणि क्षेत्रभेट व्हिडिओ एकाच ठिकाणी."/><section className="socialWall pageSection"><div className="shell"><h2 className="mediaSectionTitle">Instagram पोस्ट आणि रील्स</h2><div className="embedGrid">{instagram.map(([title,src,url])=><Embed key={url} title={title} src={src} url={url}/>)}</div><h2 className="mediaSubhead">YouTube माहितीपट आणि क्षेत्रभेटी</h2><div className="videoGrid">{videos.map(([id,title])=><article key={id}><div className="videoFrame"><iframe src={`https://www.youtube-nocookie.com/embed/${id}`} title={title} loading="lazy" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe></div><b>{title}</b><span>मूळ व्हिडिओ संबंधित YouTube प्रकाशकाकडे होस्ट आहे</span></article>)}</div><p className="embedPolicy">एम्बेडचा हक्क संबंधित प्रकाशकाकडे आहे. प्रकाशकाने पोस्ट किंवा व्हिडिओ काढल्यास तो येथे दिसणार नाही.</p></div></section></Layout>}

function Sources(){return <section className="sources"><div className="shell"><p className="sectionNo">०५ / स्रोत नोंदणी</p><div className="sourceHead"><h2>नोंदी स्वतः<br/>वाचा.</h2><p>शासकीय, संस्थात्मक आणि प्रकाशित स्रोतांच्या थेट नोंदी.</p></div><div className="sourceList">{sources.map(([title,publisher,url],i)=><a href={url} target="_blank" rel="noreferrer" key={url}><span>{String(i+1).padStart(2,"0")}</span><div><b>{title}</b><small>{publisher}</small></div><i>↗</i></a>)}</div></div></section>}

const pages:Record<Page,()=>React.JSX.Element>={home:Home,history:History,"latest-news":LatestNews,midc:Midc,blog:Blog,media:Media};
export default function App(){const Current=pages[page]||Home;return <Current/>}
